services:
  api01:
    container_name: api01
    build: ./api
    ports:
      - "3000:3000"
    environment:
      - MESSAGE=Jesus Quinde
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - DB_PORT=5432
    networks:
      - app-network

  api02:
    container_name: api02
    build: ./api
    ports:
      - "3001:3000"
    environment:
      - MESSAGE=Jesus Quinde
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - DB_PORT=5432
    networks:
      - app-network

  api03:
    container_name: api03
    build: ./api
    ports:
      - "3002:3000"
    environment:
      - MESSAGE=Jesus Quinde
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=db
      - DB_PORT=5432
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local